---
title: 'Group 1: Result comparison'
author: 
- Luca Visser
date: 2022
output:
  pdf_document:
    dev: png
    toc: true
  html_document:
    df_print: paged
    toc: true
header-includes: \setlength{\emergencystretch}{3em}
---

```{r global_options, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(fig.align = 'center')
knitr::opts_chunk$set(out.width = '60%')
knitr::opts_chunk$set(fig.width=12, fig.height=8)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

# Load data
```{r}
results_files <- list.files(pattern = ".*.txt")
for (i in 1:length(results_files)) { #loop through .txt files, assign them to their respective variables
assign(sub("\\..*","",results_files[i]), read.table(results_files[i]))
}
```

# Comparison of RNA-seq and expression micro-array

```{r}
head(RNAseq_results)
head(limmaExprsArray_results)
```

```{r}
ENS <- gsub(".*\\.","",rownames(limmaExprsArray_results))
ENS_uniq <- ENS[!(duplicated(ENS) | is.na(ENS))]
Arr_filtered <- limmaExprsArray_results[!(duplicated(ENS) | is.na(ENS)),]
rownames(Arr_filtered) <- ENS_uniq
present_in_both <- intersect(ENS_uniq, rownames(RNAseq_results))
length(present_in_both)
```

```{r}
RNAseq_filtered <- RNAseq_results[which(rownames(RNAseq_results) %in% present_in_both), ]
Arr_filtered <- Arr_filtered[which(gsub(".*\\.", "", rownames(Arr_filtered)) %in% present_in_both), ]
RNAseq_filtered <- RNAseq_filtered[order(rownames(RNAseq_filtered)), ]
Arr_filtered <- Arr_filtered[order(rownames(Arr_filtered)), ]
sign_RNA <- as.factor(RNAseq_filtered$FDR < 0.05)
sign_arr <- as.factor(Arr_filtered$adj.P.Val < 0.05)
sign_combined <- as.factor(paste(as.double(sign_RNA),as.double(sign_arr), sep="."))

plot(RNAseq_filtered$logFC, Arr_filtered$logFC, pch=20, xlab="logFC in RNA-seq", ylab="logFC in expression array", cex=0.50, col=sign_combined)
```

```{r}
print("Percentage of genes with same sign in their logFCs:")
paste(substr(as.character(sum(sign(RNAseq_filtered$logFC) == sign(Arr_filtered$logFC))/
length(RNAseq_filtered$logFC)*100),1,5), "%", sep="")
```

```{r}
print("Percentage of genes which are significantly DE for both analyses (blue in plot) with same sign in their logFCs:")
paste(substr(as.character(sum((sign(RNAseq_filtered$logFC) == sign(Arr_filtered$logFC))
[as.character(sign_combined)=="2.2"])/sum(as.character(sign_combined)=="2.2")*100),1,5),
"%", sep="")
```

# Venn diagram
```{r}
library(ggVennDiagram)
library(ggplot2)

Arr.up <- rownames(Arr_filtered[Arr_filtered$logFC > 0 & Arr_filtered$adj.P.Val < 0.05,])
Arr.down <- rownames(Arr_filtered[Arr_filtered$logFC < 0 & Arr_filtered$adj.P.Val < 0.05,])

Seq.up <- rownames(RNAseq_filtered[RNAseq_filtered$logFC > 0 & RNAseq_filtered$FDR < 0.05,])
Seq.down <- rownames(RNAseq_filtered[RNAseq_filtered$logFC < 0 & RNAseq_filtered$FDR < 0.05,])

venn_up <- ggVennDiagram(list("Microarray" = Arr.up, "RNA-seq" = Seq.up)) + 
  labs(title="Upregulated DE genes")
print(venn_up)

venn_down <- ggVennDiagram(list("Microarray" = Arr.down, "RNA-seq" = Seq.down)) + 
  labs(title="Downregulated DE genes")
print(venn_down)

venn_all <- ggVennDiagram(list("Microarray" = append(Arr.up, Arr.down), "RNA-seq" = append(Seq.up, Seq.down))) + 
  labs(title="All DE genes")
print(venn_all)
```


# Gene set analysis

```{r}
RNAterms <- rownames(RNAseq_GSA_results)
Arrterms <- rownames(array_GSA_results)

venn_GO <- ggVennDiagram(list("Microarray" = Arrterms, "RNA-seq" = RNAterms)) + 
  labs(title="GO terms")
print(venn_GO)
```
```{r}
library(dplyr)

common_arr <- array_GSA_results[Arrterms %in% intersect(RNAterms, Arrterms), ] %>%
  rename("DE.Array" = DE) %>%
  rename("P.Array" = P.DE) %>%
  rename("FDR.Array" = FDR.DE)
common_seq <- RNAseq_GSA_results[RNAterms %in% intersect(RNAterms, Arrterms), ] %>%
  rename("DE.RNAseq" = DE) %>%
  rename("P.RNAseq" = P.DE) %>%
  rename("FDR.RNAseq" = FDR.DE)

print(common_arr)
print(common_seq)
```

```{r include = FALSE}
# Generate pngs
png("fcplot.png")
plot(RNAseq_filtered$logFC, Arr_filtered$logFC, pch=20, xlab="logFC in RNA-seq", ylab="logFC in expression array", cex=0.50, col=sign_combined)
dev.off()

png("venn_up.png")
print(venn_up)
dev.off()

png("venn_down.png")
print(venn_down)
dev.off()

png("venn_all.png")
print(venn_all)
dev.off()

# Generate tables
library(xtable)
common <- merge(common_arr, common_seq) %>%
  arrange(FDR.RNAseq) %>%
  select(c("Term", "Ont", "N", "DE.Array", "DE.RNAseq", "P.Array", "P.RNAseq", "FDR.Array", "FDR.RNAseq"))
print(common)
xtable(common, type = "latex", file = "GSAt10.tex", digits = c(2, 2, 2, 2, 2, 2, -2, -2, -2, -2))
```










